baseURL = "https://link.fauzihermawan.com/"
languageCode = "en-us"
title = "Fauzi Ramadhan Hermawan Link"
theme = "LucentLink-Hugo"
minVersion = "0.115.0"

[params]
  description     = "Fauzi Ramadhan Hermawan Link Website"
  googleAnalytics = ""    # your GA ID, if any

[outputs]
  home = ["HTML"]